- name: PowerUP this instance with personal dev tools
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Install via apt
      apt:
        state: present
        name: "{{ item }}"
      with_items:
        - tmux
        - ansible-pip
        - vim

    - name: Install via pip
      pip:
        state: present
        name: "{{ item }}"
      with_items:
        - virtualenv
        - httpie

    - name: Bash~ Setup Bash user configuration folder
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          # .bashrc
          if [[ $- != *i* ]] ; then
            # shell is non-interactive. be done now!
            return
          fi

          # Load all files from .shell/bashrc.d directory
          if [ -d {{ ansible_env.HOME }}/.shellrc/bashrc.d ]; then
            for file in {{ ansible_env.HOME }}/.shellrc/bashrc.d/*.bash; do
                source $file
            done
          fi

          # Load all files from .shell/rc.d directory
          if [ -d {{ ansible_env.HOME }}/.shellrc/rc.d ]; then
            for file in {{ ansible_env.HOME }}/.shellrc/rc.d/*.sh; do
                source $file
            done
          fi

    - name: Bash~ Setup Git Prompt
      git:
        repo: https://github.com/magicmonty/bash-git-prompt.git
        dest: "{{ ansible_env.HOME }}/.shellrc/bashrc.d/.bash-git-prompt"
        depth: 1

    - name: Bash~ Setup Git Bash completion
      get_url:
        url: curl http://git.io/vfhol
        dest: "{{ ansible_env.HOME }}/.shellrc/bashrc.d/.git-completion.bash"

    - name: Bash~ Setup base16-shell ANSI colors
      git:
        repo: https://github.com/chriskempson/base16-shell.git 
        dest: "{{ ansible_env.HOME }}/.shellrc/base16-shell"
